# Generated by Django 3.2.18 on 2023-04-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('imgpath', models.CharField(max_length=100)),
                ('sellflag', models.BooleanField(default=True)),
            ],
        ),
    ]
