# Generated by Django 3.2.18 on 2023-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
