# Generated by Django 3.2.18 on 2023-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengerapp', '0002_auto_20230430_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='Auto', max_length=6, null=True),
        ),
    ]
